config/routes.rb
WorldBankLoans::Application.routes.draw do
  # The data to display on the map
  match "country_data/:action(.:format)", :to => "country_data"
  
  resources :countries, :only => [ :index, :show ] do
    resources :projects,  :only => [ :index, :show ]
  end
  resources :loans,  :only => [ :show ]
  
  root :to => "welcome#index"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>CTR Open Data Demo</h1>
<p>Information goes here</p>
<%= link_to "View map", countries_path %>

app/views/welcome/index.mobile.erb
<div class="toolbar">
  <h1 id="pageTitle">CTR Open Data Demo</h1>
  <%= link_to "", "#", :id => "backButton", :class => "button" %>
</div>

<div id="Welcome" class="panel" selected="true" title="Welcome">
  <ul>
    <li class="ctr-logo">
      <%=image_tag "ctr_logo.jpg", :alt => "CTR Open Data Beta"%>
    </li>
    <li>
      <%=link_to "View undisbursed loans", "#MapContainer", :id => "view_undisbursed_loans"%>
    </li>
    <li>
      <%=link_to "View disbursed loans", "#MapContainer", :id => "view_disbursed_loans"%>
    </li>
  </ul>
  <h2>Note -- the data in the app is provisional and often inaccurate. It does 
  not represent actual World Bank data. Please do not reuse it.  For questions, 
  please contact <%= mail_to "smoscoso@worldbank.org"%></h2>
</div>

<div id="MapContainer" title="Map">
  <div id="map">
  </div>
  
  <div id="Navigation">
    <table>
      <tr>
        <td align="center">
          <div id="undisbursed_percent" class="option" selected="progress">
            <div class="description">Undisbursed</div>
            <div class="symbol">%</div>
          </div>
        </td>
        <td align="center">
          <div id="undisbursed_amount" class="option">
            <div class="description">Undisbursed</div>
            <div class="symbol">$bn</div>
          </div>
        </td>
        <td align="center">
          <div id="disbursed_percent" class="option">
            <div class="description">Disbursed</div>
            <div class="symbol">%</div>
          </div>
        </td>
        <td align="center">
          <div id="disbursed_amount" class="option">
            <div class="description">Disbursed</div>
            <div class="symbol">$bn</div>
          </div>
        </td>
      </tr>
    </table>
  </div>
</div>

<form id="Track" class="dialog" action="">
    <fieldset>
        <h1>Sorry, this feature is not available yet</h1>
        <%=link_to "Ok", "", :type => "cancel", :class => "grayButton"%>
    </fieldset>
</form>

<form id="Report" class="dialog" action="">
    <fieldset>
        <h1>Report this project.</h1>
        <div><%=link_to "Upload photo", "javascript:alert(\"Sorry, this feature is not available\");", :class => "whiteButton"%></div>
        <div><%=link_to "Report fraud", "javascript:alert(\"Sorry, this feature is not available\");", :class => "whiteButton"%></div>
        <div><%=link_to "Rate this project", "javascript:alert(\"Sorry, this feature is not available\");", :class => "whiteButton"%></div>
        <div><%=link_to "General comment", "javascript:alert(\"Sorry, this feature is not available\");", :class => "whiteButton"%></div>
        <div><%=link_to "Cancel", nil, :class => "grayButton", :type => "cancel"%></div>
    </fieldset>
</form>