config/routes.rb
WorldBankLoans::Application.routes.draw do
  # The data to display on the map
  match "country_data/:action(.:format)", :to => "country_data"
  
  resources :countries, :only => [ :index, :show ] do
    resources :projects,  :only => [ :index, :show ]
  end
  resources :loans,  :only => [ :show ]
  
  root :to => "welcome#index"
end

app/models/project.rb
require 'socrata/data'

# Each project has a number of loans associated with it
class Project
  
  attr_accessor :loans
  
  def initialize(loan_data)
    self.loans = [loan_data]
  end
  
  def name
    self.loans[0].project
  end
  
  def id
    self.loans[0].id
  end
  
  def has_multiple_loans?
    loans.size > 1
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout nil, :only => :mobile
  
  def show
    @project = Country.find(params[:country_id]).project(params[:id])
  end
  
  def index
    @country = Country.find(params[:country_id])
    @projects = @country.projects.paginate(params[:page])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.mobile.erb
<% @projects.each do |project| %>
  <% unless project.has_multiple_loans? %>
    <li><%= link_to project.name, loan_path(:id => project.loans[0].id) %></li>
  <% else %>
    <li><%= link_to "#{project.name} (#{project.loans.size})", country_project_path(@country.id, project.id) %></li>
  <% end %>
<% end %>

<% unless @projects.current_page == @projects.total_pages %>
  <li><%= link_to "View more...", country_projects_path(@country.id, :page => @projects.current_page + 1), :target => "_replace" %></li>
<% end %>

app/views/projects/show.mobile.erb
<ul id="project-<%=@project.id%>" title="<%=@project.name%>">
  <% @project.loans.each do |loan| %>
    <li><%=link_to loan.name, loan_path(:id => loan.id)%></li>
  <% end %>
</ul>